window.hjSiteSettings = window.hjSiteSettings || {"testers_widgets":[],"surveys":[],"record_targeting_rules":[],"recording_capture_keystrokes":true,"polls":[{"persist_condition":"once","targeting":[{"negate":false,"pattern":"desktop","match_operation":"exact","component":"device"},{"negate":false,"pattern":"tablet","match_operation":"exact","component":"device"},{"negate":false,"pattern":"phone","match_operation":"exact","component":"device"},{"negate":false,"pattern":"osj","match_operation":"contains","component":"url"},{"negate":false,"pattern":"oss","match_operation":"contains","component":"url"},{"negate":false,"pattern":"osk","match_operation":"contains","component":"url"},{"negate":true,"pattern":"journal","match_operation":"contains","component":"url"}],"language":"en","targeting_percentage":100,"created_epoch_time":1449151760,"display_condition":"delay","content":{"thankyou":"Thank you for answering this Poll. Your feedback is highly appreciated! If we can help with any questions, please contact us on info@oliverspencer.co.uk","questions":[{"nextByAnswer":[],"text":"Is there anything missing from this page? Please let us know.","labels":null,"answers":null,"next":"thankYou","type":"single-open-ended-multiple-line","randomize_answer_order":false}]},"effective_show_branding":true,"background":"#333333","skin":"dark","position":"right","display_delay":15,"id":20629},{"persist_condition":"response","targeting":[{"negate":false,"pattern":"checkout\/onepage\/success","match_operation":"contains","component":"url"},{"negate":false,"pattern":"phone","match_operation":"exact","component":"device"},{"negate":false,"pattern":"tablet","match_operation":"exact","component":"device"},{"negate":false,"pattern":"desktop","match_operation":"exact","component":"device"}],"language":"en","targeting_percentage":100,"created_epoch_time":1447345162,"display_condition":"immediate","content":{"thankyou":"Thank you for answering this Poll. Your feedback is highly appreciated! If we can help with any questions, please do email info@oliverspencer.co.uk or call +44 (0)207 242 5173.","questions":[{"nextByAnswer":[],"text":"What could we have done to make your visit better? Please let us know.","labels":null,"answers":null,"next":"byOrder","type":"single-open-ended-multiple-line","randomize_answer_order":false}]},"effective_show_branding":true,"background":"#333333","skin":"dark","position":"right","display_delay":0,"id":18789}],"site_id":67387,"forms":[],"record":false,"heatmaps":[],"deferred_page_contents":[],"feedback_widgets":[],"r":0.6944444444};

window.hjBootstrap = window.hjBootstrap || function (scriptUrl) {
    var s = document.createElement('script');
    s.src = scriptUrl;
    document.getElementsByTagName('head')[0].appendChild(s);
    window.hjBootstrap = function() {};
};

hjBootstrap('https://script.hotjar.com/modules-3f929be33bd5955c682d06614328f081.js');